blank_issues_enabled: false
contact_links:
  - name: 📃 Documentation Issue
    url:  https://github.com/red-armor/infinite-list/issues/new
    about: This issue tracker is not for documentation issues. Please file documentation issues here.