export const DEFAULT_ITEM_APPROXIMATE_LENGTH = 80;
export const LAYOUT_EQUAL_CORRECTION_VALUE = 0.5;
export const DEFAULT_RECYCLER_TYPE = '__default_recycler_buffer__';
export const DEFAULT_DIMENSION_ITEM_APPROXIMATE_LENGTH = 1;
