const a = {
  '@infinite-list/base-dimensions': '/Users/ryuyutyo/Documents/code/red/infinite-list/core/base-dimensions/src',
  '@infinite-list/container': '/Users/ryuyutyo/Documents/code/red/infinite-list/core/container/src',
  '@infinite-list/dimensions-model': '/Users/ryuyutyo/Documents/code/red/infinite-list/core/dimensions-model/src',
  '@infinite-list/disposable': '/Users/ryuyutyo/Documents/code/red/infinite-list/core/disposable/src',
  '@infinite-list/intersection': '/Users/ryuyutyo/Documents/code/red/infinite-list/core/intersection/src',
  '@infinite-list/intersection-observer': '/Users/ryuyutyo/Documents/code/red/infinite-list/core/intersection-observer/src',
  '@infinite-list/item-meta': '/Users/ryuyutyo/Documents/code/red/infinite-list/core/item-meta/src',
  '@infinite-list/scheduler': '/Users/ryuyutyo/Documents/code/red/infinite-list/core/scheduler/src',
  '@infinite-list/state': '/Users/ryuyutyo/Documents/code/red/infinite-list/core/state/src',
  '@infinite-list/strategies': '/Users/ryuyutyo/Documents/code/red/infinite-list/core/strategies/src',
  '@infinite-list/types': '/Users/ryuyutyo/Documents/code/red/infinite-list/core/types/src',
  '@infinite-list/utils': '/Users/ryuyutyo/Documents/code/red/infinite-list/core/utils/src',
  '@infinite-list/viewable': '/Users/ryuyutyo/Documents/code/red/infinite-list/core/viewable/src',
  '@infinite-list/dimension': '/Users/ryuyutyo/Documents/code/red/infinite-list/model/dimension/src',
  '@infinite-list/group-dimensions': '/Users/ryuyutyo/Documents/code/red/infinite-list/model/group-dimensions/src',
  '@infinite-list/items-dimensions': '/Users/ryuyutyo/Documents/code/red/infinite-list/model/items-dimensions/src',
  '@infinite-list/list-dimensions': '/Users/ryuyutyo/Documents/code/red/infinite-list/model/list-dimensions/src',
  '@infinite-list/masonry-dimensions': '/Users/ryuyutyo/Documents/code/red/infinite-list/model/masonry-dimensions/src',
  '@infinite-list/pseudo-list-dimensions': '/Users/ryuyutyo/Documents/code/red/infinite-list/model/pseudo-list-dimensions/src',
  '@infinite-list/group': '/Users/ryuyutyo/Documents/code/red/infinite-list/ui/group/src',
  '@infinite-list/list': '/Users/ryuyutyo/Documents/code/red/infinite-list/ui/list/src',
  '@infinite-list/masonry': '/Users/ryuyutyo/Documents/code/red/infinite-list/ui/masonry/src',
  '@infinite-list/scroller': '/Users/ryuyutyo/Documents/code/red/infinite-list/ui/scroller/src',
  react: '/Users/ryuyutyo/Documents/code/red/infinite-list/examples/ReactNativeListPlayground/node_modules/react',
  'react-dom': '/Users/ryuyutyo/Documents/code/red/infinite-list/examples/ReactNativeListPlayground/node_modules/react-dom',
  'react-native': '/Users/ryuyutyo/Documents/code/red/infinite-list/examples/ReactNativeListPlayground/node_modules/react-native'
}

const b = [
  '/Users/ryuyutyo/Documents/code/red/infinite-list/core/base-dimensions/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/core/container/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/core/dimensions-model/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/core/disposable/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/core/intersection/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/core/intersection-observer/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/core/item-meta/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/core/scheduler/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/core/state/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/core/strategies/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/core/types/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/core/utils/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/core/viewable/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/model/dimension/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/model/group-dimensions/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/model/items-dimensions/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/model/list-dimensions/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/model/masonry-dimensions/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/model/pseudo-list-dimensions/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/ui/group/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/ui/list/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/ui/masonry/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/ui/scroller/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/core/base-dimensions/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/core/container/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/core/dimensions-model/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/core/disposable/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/core/intersection/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/core/intersection-observer/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/core/item-meta/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/core/scheduler/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/core/state/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/core/strategies/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/core/types/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/core/utils/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/core/viewable/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/model/dimension/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/model/group-dimensions/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/model/items-dimensions/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/model/list-dimensions/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/model/masonry-dimensions/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/model/pseudo-list-dimensions/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/ui/group/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/ui/list/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/ui/masonry/src',
  '/Users/ryuyutyo/Documents/code/red/infinite-list/ui/scroller/src'
]







resolve -----  {
  '@infinite-list/data-model': '/Users/ryuyutyo/Documents/code/red/infinite-list/packages/data-model/src',
  '@x-oasis/batchinator': '/Users/ryuyutyo/Documents/code/red/infinite-list/packages/data-model/node_modules/@x-oasis/batchinator',
  '@x-oasis/is-ref': '/Users/ryuyutyo/Documents/code/red/infinite-list/packages/data-model/node_modules/@x-oasis/is-ref',
  '@x-oasis/noop': '/Users/ryuyutyo/Documents/code/red/infinite-list/packages/data-model/node_modules/@x-oasis/noop',
  '@x-oasis/select-value': '/Users/ryuyutyo/Documents/code/red/infinite-list/packages/data-model/node_modules/@x-oasis/select-value',
  '@x-oasis/shallow-equal': '/Users/ryuyutyo/Documents/code/red/infinite-list/packages/data-model/node_modules/@x-oasis/shallow-equal',
  '@x-oasis/throttle': '/Users/ryuyutyo/Documents/code/red/infinite-list/packages/data-model/node_modules/@x-oasis/throttle',
  '@x-oasis/batchinate-last': '/Users/ryuyutyo/Documents/code/red/infinite-list/packages/data-model/node_modules/@x-oasis/batchinate-last',
  '@x-oasis/capitalize': '/Users/ryuyutyo/Documents/code/red/infinite-list/packages/data-model/node_modules/@x-oasis/capitalize',
  '@x-oasis/default-boolean-value': '/Users/ryuyutyo/Documents/code/red/infinite-list/packages/data-model/node_modules/@x-oasis/default-boolean-value',
  '@x-oasis/default-value': '/Users/ryuyutyo/Documents/code/red/infinite-list/packages/data-model/node_modules/@x-oasis/default-value',
  '@x-oasis/find-last-index': '/Users/ryuyutyo/Documents/code/red/infinite-list/packages/data-model/node_modules/@x-oasis/find-last-index',
  '@x-oasis/get-map-key-by-value': '/Users/ryuyutyo/Documents/code/red/infinite-list/packages/data-model/node_modules/@x-oasis/get-map-key-by-value',
  '@x-oasis/is-clamped': '/Users/ryuyutyo/Documents/code/red/infinite-list/packages/data-model/node_modules/@x-oasis/is-clamped',
  '@x-oasis/is-object': '/Users/ryuyutyo/Documents/code/red/infinite-list/packages/data-model/node_modules/@x-oasis/is-object',
  '@x-oasis/layout-equal': '/Users/ryuyutyo/Documents/code/red/infinite-list/packages/data-model/node_modules/@x-oasis/layout-equal',
  '@x-oasis/omit': '/Users/ryuyutyo/Documents/code/red/infinite-list/packages/data-model/node_modules/@x-oasis/omit',
  '@x-oasis/prefix-interval-tree': '/Users/ryuyutyo/Documents/code/red/infinite-list/packages/data-model/node_modules/@x-oasis/prefix-interval-tree',
  '@x-oasis/recycler': '/Users/ryuyutyo/Documents/code/red/infinite-list/packages/data-model/node_modules/@x-oasis/recycler',
  '@x-oasis/resolve-changed': '/Users/ryuyutyo/Documents/code/red/infinite-list/packages/data-model/node_modules/@x-oasis/resolve-changed',
  '@x-oasis/shallow-array-equal': '/Users/ryuyutyo/Documents/code/red/infinite-list/packages/data-model/node_modules/@x-oasis/shallow-array-equal',
  '@x-oasis/unique-array-object': '/Users/ryuyutyo/Documents/code/red/infinite-list/packages/data-model/node_modules/@x-oasis/unique-array-object',
  'memoize-one': '/Users/ryuyutyo/Documents/code/red/infinite-list/packages/data-model/node_modules/memoize-one',
  tslib: '/Users/ryuyutyo/Documents/code/red/infinite-list/packages/data-model/node_modules/tslib',
  '@infinite-list/item-meta': '/Users/ryuyutyo/Documents/code/red/infinite-list/core/item-meta/src',
  '@infinite-list/masonry-dimensions': '/Users/ryuyutyo/Documents/code/red/infinite-list/model/masonry-dimensions/src',
  '@infinite-list/scroller': '/Users/ryuyutyo/Documents/code/red/infinite-list/ui/scroller/src',
  '@infinite-list/strategies': '/Users/ryuyutyo/Documents/code/red/infinite-list/core/strategies/src',
  '@infinite-list/types': '/Users/ryuyutyo/Documents/code/red/infinite-list/core/types/src',
  '@infinite-list/scheduler': '/Users/ryuyutyo/Documents/code/red/infinite-list/core/scheduler/src',
  '@infinite-list/disposable': '/Users/ryuyutyo/Documents/code/red/infinite-list/core/disposable/src',
  '@infinite-list/items-dimensions': '/Users/ryuyutyo/Documents/code/red/infinite-list/model/items-dimensions/src',
  '@infinite-list/intersection-observer': '/Users/ryuyutyo/Documents/code/red/infinite-list/core/intersection-observer/src',
  '@infinite-list/dimensions-model': '/Users/ryuyutyo/Documents/code/red/infinite-list/core/dimensions-model/src',
  '@infinite-list/list-dimensions': '/Users/ryuyutyo/Documents/code/red/infinite-list/model/list-dimensions/src',
  '@infinite-list/utils': '/Users/ryuyutyo/Documents/code/red/infinite-list/core/utils/src',
  '@infinite-list/group-dimensions': '/Users/ryuyutyo/Documents/code/red/infinite-list/model/group-dimensions/src',
  react: '/Users/ryuyutyo/Documents/code/red/infinite-list/examples/ReactNativeListPlayground/node_modules/react',
  'react-dom': '/Users/ryuyutyo/Documents/code/red/infinite-list/examples/ReactNativeListPlayground/node_modules/react-dom',
  'react-native': '/Users/ryuyutyo/Documents/code/red/infinite-list/examples/ReactNativeListPlayground/node_modules/react-native',
  '@infinite-list/react-native': '/Users/ryuyutyo/Documents/code/red/infinite-list/packages/react-native/src',
  '@infinite-list/base-dimensions': '/Users/ryuyutyo/Documents/code/red/infinite-list/core/base-dimensions/src',
  '@infinite-list/container': '/Users/ryuyutyo/Documents/code/red/infinite-list/core/container/src',
  '@infinite-list/state': '/Users/ryuyutyo/Documents/code/red/infinite-list/core/state/src',
  '@infinite-list/viewable': '/Users/ryuyutyo/Documents/code/red/infinite-list/core/viewable/src',
  '@infinite-list/dimension': '/Users/ryuyutyo/Documents/code/red/infinite-list/model/dimension/src',
  '@infinite-list/list': '/Users/ryuyutyo/Documents/code/red/infinite-list/ui/list/src',
  '@infinite-list/group': '/Users/ryuyutyo/Documents/code/red/infinite-list/ui/group/src',
  '@infinite-list/masonry': '/Users/ryuyutyo/Documents/code/red/infinite-list/ui/masonry/src'
}